on:
  push:
    branches:
      - main
name: Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        
        with:
          server: ${{ secrets.SV14837_SERVER }}
          username: ${{ secrets.GITHUBTEST_USERNAME }}
          password: ${{ secrets.GITHUBTEST_PASSWORD }}
          local-dir: ./
          server-dir: /githubtest.xsrv.jp/public_html/wp-content/themes/test
          ARGS: --delete --parallel=10
